//
//  AboutView.swift
//  ZoneScope
//
//  Created by Stephen Roe on 3/12/26.
//

import SwiftUI

struct AboutView: View {
    @Environment(\.dismiss) private var dismiss

    private var versionString: String {
        let version = Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String ?? "—"
        let build = Bundle.main.infoDictionary?["CFBundleVersion"] as? String ?? "—"
        return "Version \(version) (\(build))"
    }

    var body: some View {
        NavigationStack {
            List {
                Section {
                    VStack(spacing: 8) {
                        Image(systemName: "chart.bar.xaxis")
                            .font(.largeTitle)
                            .foregroundStyle(.tint)
                        Text("ZoneScope")
                            .font(.title2)
                            .bold()
                        Text("ZoneScope shows how much time you spend in each heart-rate training zone, using workouts and heart-rate data from Apple Health.")
                            .font(.subheadline)
                            .foregroundStyle(.secondary)
                            .multilineTextAlignment(.center)
                    }
                    .frame(maxWidth: .infinity)
                    .padding(.vertical)
                    .listRowBackground(Color.clear)
                }

                Section("Features") {
                    AboutFeatureRow(
                        systemImage: "chart.bar",
                        title: "Day & Week",
                        detail: "Your zone breakdown as a bar chart for the last day or week."
                    )
                    AboutFeatureRow(
                        systemImage: "calendar",
                        title: "History",
                        detail: "Weekly zone trends as stacked bars across the past year."
                    )
                    AboutFeatureRow(
                        systemImage: "slider.horizontal.3",
                        title: "Zone filter",
                        detail: "Show or hide individual zones to focus on what matters."
                    )
                }

                Section("How zones are calculated") {
                    Text("Zones come from your heart-rate samples using the Heart Rate Reserve (Karvonen) method — (HR − resting) ÷ (max − resting) — split into five zones at 60%, 70%, 80%, and 90%. Maximum heart rate is estimated from your age; resting heart rate comes from Health.")
                        .font(.subheadline)
                }

                Section("Privacy") {
                    Text("ZoneScope reads your Health data read-only and works entirely on your device. It writes nothing back and has no network access, accounts, or tracking.")
                        .font(.subheadline)
                }

                Section {
                    Text("ZoneScope is an experimental, in-development app — largely generated by Claude Code. It isn't intended for App Store distribution.")
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                } footer: {
                    Text(versionString)
                }
            }
            .navigationTitle("About")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .confirmationAction) {
                    Button("Done") { dismiss() }
                }
            }
        }
    }
}

#Preview {
    AboutView()
}
